# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
invite_codes: &invite_codes
  '8ONEC':
    locale: 'en'
    origin: 'en'
    type: 'default'
  '593X1':
    locale: 'en'
    origin: 'en'
    type: 'in_person'
  'striatum-en':
    locale: 'en'
    origin: 'en'
    type: 'in_person'
  '3NX3H':
    locale: 'en'
    origin: 'en'
    type: 'fast_forward'
  'injection-en':
    locale: 'en'
    origin: 'en'
    type: 'fast_forward'
  'XAYOT':
    locale: 'en-gb'
    origin: 'gb'
    type: 'default'
  'DGXWA':
    locale: 'en-gb'
    origin: 'gb'
    type: 'in_person'
  'striatum-en-gb':
    locale: 'en-gb'
    origin: 'gb'
    type: 'in_person'
  'APNZ5':
    locale: 'en-gb'
    origin: 'gb'
    type: 'fast_forward'
  'injection-en-gb':
    locale: 'en-gb'
    origin: 'gb'
    type: 'fast_forward'
  '2EGKW':
    locale: 'de'
    origin: 'de'
    type: 'default'
  'OJBHO':
    locale: 'de'
    origin: 'de'
    type: 'in_person'
  'striatum-de':
    locale: 'de'
    origin: 'de'
    type: 'in_person'
  '1LG9X':
    locale: 'de'
    origin: 'de'
    type: 'fast_forward'
  'injection-de':
    locale: 'de'
    origin: 'de'
    type: 'fast_forward'
  'IFDUA':
    locale: 'de-at'
    origin: 'at'
    type: 'default'
  'IQSY9':
    locale: 'de-at'
    origin: 'at'
    type: 'in_person'
  'striatum-de-at':
    locale: 'de-at'
    origin: 'at'
    type: 'in_person'
  'DIMKF':
    locale: 'de-at'
    origin: 'at'
    type: 'fast_forward'
  'injection-de-at':
    locale: 'de-at'
    origin: 'at'
    type: 'fast_forward'
  'OB1ZO':
    locale: 'fr'
    origin: 'fr'
    type: 'default'
  'IFXJ8':
    locale: 'fr'
    origin: 'fr'
    type: 'in_person'
  'striatum-fr':
    locale: 'fr'
    origin: 'fr'
    type: 'in_person'
  'SMCT5':
    locale: 'fr'
    origin: 'fr'
    type: 'fast_forward'
  'injection-fr':
    locale: 'fr'
    origin: 'fr'
    type: 'fast_forward'
  'IYQQO':
    locale: 'it'
    origin: 'it'
    type: 'default'
  'Q594R':
    locale: 'it'
    origin: 'it'
    type: 'in_person'
  'striatum-it':
    locale: 'it'
    origin: 'it'
    type: 'in_person'
  '8XNGO':
    locale: 'it'
    origin: 'it'
    type: 'fast_forward'
  'injection-it':
    locale: 'it'
    origin: 'it'
    type: 'fast_forward'
  'QYIE4':
    locale: 'es'
    origin: 'es'
    type: 'default'
  'ZBQXH':
    locale: 'es'
    origin: 'es'
    type: 'in_person'
  'striatum-es':
    locale: 'es'
    origin: 'es'
    type: 'in_person'
  '89RFQ':
    locale: 'es'
    origin: 'es'
    type: 'fast_forward'
  'injection-es':
    locale: 'es'
    origin: 'es'
    type: 'fast_forward'
  'vzmylinvite349':
    locale: 'en'
    origin: 'en'
    type: 'default'
  'ausvzmylinvite':
    locale: 'en'
    origin: 'at'
    type: 'default'
  'amyloid':
    locale: 'en'
    origin: 'en'
    type: 'default'
  'emission':
    locale: 'en-gb'
    origin: 'gb'
    type: 'default'
  'positron':
    locale: 'de'
    origin: 'de'
    type: 'default'
  'resonance':
    locale: 'de-at'
    origin: 'at'
    type: 'default'
  'sagittal':
    locale: 'fr'
    origin: 'fr'
    type: 'default'
  'plaque':
    locale: 'it'
    origin: 'it'
    type: 'default'
  'tomography':
    locale: 'es'
    origin: 'es'
    type: 'default'

test: &test
  secret_key_base: d38e5e398cf6c52255e2b370d89eff7129fcce95f9c6140016e4db3ec98f0054197b464b6edba50943dfbba26a73d5c6698749b43a82e0b828172a1f2275ea94

development: &development
  secret_key_base: 4b746f750ff54b449337e06bdb76637c0e5a0c8141385904a551a6ab5791164d6abe34e516bf8f6c1d10c38cac754bf568d1ac2a9297e6995565a7aa8dbc6efd
  asset_host: 'dxugyqzjahy7a.cloudfront.net'
  content_host: 'dki1hrtf104z9.cloudfront.net'
  google_analytics_key: 'UA-56326872-1'
  invite_codes:
    <<: *invite_codes

staging: &staging
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  asset_host: 'dxugyqzjahy7a.cloudfront.net'
  content_host: 'dki1hrtf104z9.cloudfront.net'
  google_analytics_key: 'UA-56326872-1'
  invite_codes:
    <<: *invite_codes

sandbox:
  <<: *staging
  asset_host: 'vizamyl-sandbox.herokuapp.com'
  invite_codes:
    <<: *invite_codes

production: &production
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  asset_host: 'assets.readvizamyl.com'
  content_host: 'content.readvizamyl.com'
  google_analytics_key: 'UA-56326872-2'
  invite_codes:
    <<: *invite_codes
