# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
invite_codes: &invite_codes
  'VIZRTHCP':
    type: 'default'
  'VIZRTCASES': 
    type: 'fast_forward'
  'VIZRTSUPERU':
    type: 'in_person'
  # '8ONEC':
  #   locale: 'en'
  #   origin: 'en'
  #   type: 'default'
  # '593X1':
  #   locale: 'en'
  #   origin: 'en'
  #   type: 'in_person'
  # 'striatum-en':
  #   locale: 'en'
  #   origin: 'en'
  #   type: 'in_person'
  # '3NX3H':
  #   locale: 'en'
  #   origin: 'en'
  #   type: 'fast_forward'
  # 'injection-en':
  #   locale: 'en'
  #   origin: 'en'
  #   type: 'fast_forward'
  # 'XAYOT':
  #   locale: 'en-gb'
  #   origin: 'gb'
  #   type: 'default'
  # 'DGXWA':
  #   locale: 'en-gb'
  #   origin: 'gb'
  #   type: 'in_person'
  # 'striatum-en-gb':
  #   locale: 'en-gb'
  #   origin: 'gb'
  #   type: 'in_person'
  # 'APNZ5':
  #   locale: 'en-gb'
  #   origin: 'gb'
  #   type: 'fast_forward'
  # 'injection-en-gb':
  #   locale: 'en-gb'
  #   origin: 'gb'
  #   type: 'fast_forward'
  # '8Q5MH':
  #   locale: 'en-us'
  #   origin: 'us'
  #   type: 'default'
  # 'TIEZM':
  #   locale: 'en-us'
  #   origin: 'us'
  #   type: 'in_person'
  # 'KN67H':
  #   locale: 'en-us'
  #   origin: 'us'
  #   type: 'fast_forward'
  # '2EGKW':
  #   locale: 'de'
  #   origin: 'de'
  #   type: 'default'
  # 'OJBHO':
  #   locale: 'de'
  #   origin: 'de'
  #   type: 'in_person'
  # 'striatum-de':
  #   locale: 'de'
  #   origin: 'de'
  #   type: 'in_person'
  # '1LG9X':
  #   locale: 'de'
  #   origin: 'de'
  #   type: 'fast_forward'
  # 'injection-de':
  #   locale: 'de'
  #   origin: 'de'
  #   type: 'fast_forward'
  # 'IFDUA':
  #   locale: 'de-at'
  #   origin: 'at'
  #   type: 'default'
  # 'IQSY9':
  #   locale: 'de-at'
  #   origin: 'at'
  #   type: 'in_person'
  # 'striatum-de-at':
  #   locale: 'de-at'
  #   origin: 'at'
  #   type: 'in_person'
  # 'DIMKF':
  #   locale: 'de-at'
  #   origin: 'at'
  #   type: 'fast_forward'
  # 'injection-de-at':
  #   locale: 'de-at'
  #   origin: 'at'
  #   type: 'fast_forward'
  # 'OB1ZO':
  #   locale: 'fr'
  #   origin: 'fr'
  #   type: 'default'
  # 'IFXJ8':
  #   locale: 'fr'
  #   origin: 'fr'
  #   type: 'in_person'
  # 'striatum-fr':
  #   locale: 'fr'
  #   origin: 'fr'
  #   type: 'in_person'
  # 'SMCT5':
  #   locale: 'fr'
  #   origin: 'fr'
  #   type: 'fast_forward'
  # 'injection-fr':
  #   locale: 'fr'
  #   origin: 'fr'
  #   type: 'fast_forward'
  # 'IYQQO':
  #   locale: 'it'
  #   origin: 'it'
  #   type: 'default'
  # 'Q594R':
  #   locale: 'it'
  #   origin: 'it'
  #   type: 'in_person'
  # 'striatum-it':
  #   locale: 'it'
  #   origin: 'it'
  #   type: 'in_person'
  # '8XNGO':
  #   locale: 'it'
  #   origin: 'it'
  #   type: 'fast_forward'
  # 'injection-it':
  #   locale: 'it'
  #   origin: 'it'
  #   type: 'fast_forward'
  # 'QYIE4':
  #   locale: 'es'
  #   origin: 'es'
  #   type: 'default'
  # 'ZBQXH':
  #   locale: 'es'
  #   origin: 'es'
  #   type: 'in_person'
  # 'striatum-es':
  #   locale: 'es'
  #   origin: 'es'
  #   type: 'in_person'
  # '89RFQ':
  #   locale: 'es'
  #   origin: 'es'
  #   type: 'fast_forward'
  # 'injection-es':
  #   locale: 'es'
  #   origin: 'es'
  #   type: 'fast_forward'
  # 'vzmylinvite349':
  #   locale: 'en'
  #   origin: 'en'
  #   type: 'default'
  # 'ausvzmylinvite':
  #   locale: 'en'
  #   origin: 'at'
  #   type: 'default'
  # 'amyloid':
  #   locale: 'en'
  #   origin: 'en'
  #   type: 'default'
  # 'emission':
  #   locale: 'en-gb'
  #   origin: 'gb'
  #   type: 'default'
  # 'positron':
  #   locale: 'de'
  #   origin: 'de'
  #   type: 'default'
  # 'resonance':
  #   locale: 'de-at'
  #   origin: 'at'
  #   type: 'default'
  # 'sagittal':
  #   locale: 'fr'
  #   origin: 'fr'
  #   type: 'default'
  # 'plaque':
  #   locale: 'it'
  #   origin: 'it'
  #   type: 'default'
  # 'tomography':
  #   locale: 'es'
  #   origin: 'es'
  #   type: 'default'
  # '3AO9Z':
  #   locale: 'en-gb'
  #   origin: 'sk'
  #   type: 'default'
  # '6NGUI':
  #   locale: 'en-gb'
  #   origin: 'sk'
  #   type: 'fast_forward'
  # 'TLX87':
  #   locale: 'en-gb'
  #   origin: 'sk'
  #   type: 'in_person'
  # 'XMQNQ':
  #   locale: 'en-gb'
  #   origin: 'si'
  #   type: 'default'
  # '14Z8W':
  #   locale: 'en-gb'
  #   origin: 'si'
  #   type: 'fast_forward'
  # 'BYJPN':
  #   locale: 'en-gb'
  #   origin: 'si'
  #   type: 'in_person'
  # 'JE5H7':
  #   locale: 'en-gb'
  #   origin: 'cz'
  #   type: 'default'
  # 'Y1BQG':
  #   locale: 'en-gb'
  #   origin: 'cz'
  #   type: 'fast_forward'
  # 'W1XZA':
  #   locale: 'en-gb'
  #   origin: 'cz'
  #   type: 'in_person'
  # 'PQ1BK':
  #   locale: 'en-gb'
  #   origin: 'hr'
  #   type: 'default'
  # 'APZK8':
  #   locale: 'en-gb'
  #   origin: 'hr'
  #   type: 'fast_forward'
  # 'FETAN':
  #   locale: 'en-gb'
  #   origin: 'hr'
  #   type: 'in_person'
  # 'KRVUK':
  #   locale: 'en-gb'
  #   origin: 'hu'
  #   type: 'default'
  # 'IXLTV':
  #   locale: 'en-gb'
  #   origin: 'hu'
  #   type: 'fast_forward'
  # 'XME7M':
  #   locale: 'en-gb'
  #   origin: 'hu'
  #   type: 'in_person'
  # '6SQO7':
  #   locale: 'en-gb'
  #   origin: 'dk'
  #   type: 'default'
  # 'D5Z4I':
  #   locale: 'en-gb'
  #   origin: 'dk'
  #   type: 'fast_forward'
  # 'N7NPH':
  #   locale: 'en-gb'
  #   origin: 'dk'
  #   type: 'in_person'
  # 'G63RW':
  #   locale: 'en-gb'
  #   origin: 'fi'
  #   type: 'default'
  # 'HARG9':
  #   locale: 'en-gb'
  #   origin: 'fi'
  #   type: 'fast_forward'
  # 'IN3X3':
  #   locale: 'en-gb'
  #   origin: 'fi'
  #   type: 'in_person'
  # 'SK6AO':
  #   locale: 'en-gb'
  #   origin: 'no'
  #   type: 'default'
  # 'BJCPJ':
  #   locale: 'en-gb'
  #   origin: 'no'
  #   type: 'fast_forward'
  # 'KCB6G':
  #   locale: 'en-gb'
  #   origin: 'no'
  #   type: 'in_person'
  # 'OP1U7':
  #   locale: 'en-gb'
  #   origin: 'ee'
  #   type: 'default'
  # '2Y8W7':
  #   locale: 'en-gb'
  #   origin: 'ee'
  #   type: 'fast_forward'
  # 'BJHCU':
  #   locale: 'en-gb'
  #   origin: 'ee'
  #   type: 'in_person'
  # 'LV7MD':
  #   locale: 'en-gb'
  #   origin: 'nl'
  #   type: 'default'
  # 'GY6B1':
  #   locale: 'en-gb'
  #   origin: 'nl'
  #   type: 'fast_forward'
  # 'WT6YQ':
  #   locale: 'en-gb'
  #   origin: 'nl'
  #   type: 'in_person'
  # '9Q1PE':
  #   locale: 'en-gb'
  #   origin: 'se'
  #   type: 'default'
  # 'KT8PL':
  #   locale: 'en-gb'
  #   origin: 'se'
  #   type: 'fast_forward'
  # '6DZQT':
  #   locale: 'en-gb'
  #   origin: 'se'
  #   type: 'in_person'
  # 'TXO8X':
  #   locale: 'en-gb'
  #   origin: 'kr'
  #   type: 'default'
  # 'VLAEN':
  #   locale: 'en-gb'
  #   origin: 'kr'
  #   type: 'fast_forward'
  # '8P32U':
  #   locale: 'en-gb'
  #   origin: 'kr'
  #   type: 'in_person'
  # '6LRA0':
  #   locale: 'en-us'
  #   origin: 'hk'
  #   type: 'default'
  # 'ZIDZZ':
  #   locale: 'en-us'
  #   origin: 'hk'
  #   type: 'fast_forward'
  # 'MW04Z':
  #   locale: 'en-us'
  #   origin: 'hk'
  #   type: 'in_person'
  # 'RN4GD':
  #   locale: 'en-us'
  #   origin: 'sg'
  #   type: 'default'
  # '8DA84':
  #   locale: 'en-us'
  #   origin: 'sg'
  #   type: 'fast_forward'
  # 'QTBVA':
  #   locale: 'en-us'
  #   origin: 'sg'
  #   type: 'in_person'
  # '4NYFN':
  #   locale: 'en-gb'
  #   origin: 'be'
  #   type: 'default'
  # 'JVMEU':
  #   locale: 'en-gb'
  #   origin: 'be'
  #   type: 'fast_forward'
  # 'MFTOT':
  #   locale: 'en-gb'
  #   origin: 'be'
  #   type: 'in_person'
  # '8OWF6':
  #   locale: 'fr'
  #   origin: 'be'
  #   type: 'default'
  # 'M2TIS':
  #   locale: 'fr'
  #   origin: 'be'
  #   type: 'fast_forward'
  # 'BOB12':
  #   locale: 'fr'
  #   origin: 'be'
  #   type: 'in_person'
  # 'QR3HK':
  #   locale: 'en-us'
  #   origin: 'au'
  #   type: 'default'
  # 'AM5WR':
  #   locale: 'en-us'
  #   origin: 'au'
  #   type: 'in_person'
  # 'HP9WT':
  #   locale: 'en-us'
  #   origin: 'au'
  #   type: 'fast_forward'
  # 'KQITH':
  #   locale: 'fr'
  #   origin: 'ch'
  #   type: 'default'
  # 'RCVTS':
  #   locale: 'fr'
  #   origin: 'ch'
  #   type: 'in_person'
  # 'MZNXQ':
  #   locale: 'fr'
  #   origin: 'ch'
  #   type: 'fast_forward'
  # 'SWTRR':
  #   locale: 'de'
  #   origin: 'ch'
  #   type: 'default'
  # 'HVLMA':
  #   locale: 'de'
  #   origin: 'ch'
  #   type: 'in_person'
  # 'LH4QZ':
  #   locale: 'de'
  #   origin: 'ch'
  #   type: 'fast_forward'
  # 'WB5PE':
  #   locale: 'it'
  #   origin: 'ch'
  #   type: 'default'
  # 'CHQYQ':
  #   locale: 'it'
  #   origin: 'ch'
  #   type: 'in_person'
  # 'BNA3E':
  #   locale: 'it'
  #   origin: 'ch'
  #   type: 'fast_forward'
  # 'UX7WZ':
  #   locale: 'jp'
  #   origin: 'jp'
  #   type: 'default'
  # '2PNWU':
  #   locale: 'jp'
  #   origin: 'jp'
  #   type: 'in_person'
  # 'ST66N':
  #   locale: 'jp'
  #   origin: 'jp'
  #   type: 'fast_forward'
  # 'LL0RD':
  #   locale: 'en-gb'
  #   origin: 'gr'
  #   type: 'default'
  # 'P2ROF':
  #   locale: 'en-gb'
  #   origin: 'gr'
  #   type: 'fast_forward'
  # 'T1DOP':
  #   locale: 'en-gb'
  #   origin: 'gr'
  #   type: 'in_person'
  # 'BRGD4':
  #   locale: 'en-us'
  #   origin: 'tw'
  #   type: 'default'
  # 'T8D48':
  #   locale: 'en-us'
  #   origin: 'tw'
  #   type: 'fast_forward'
  # 'TWVBA':
  #   locale: 'en-us'
  #   origin: 'tw'
  #   type: 'in_person'

test: &test
  secret_key_base: d38e5e398cf6c52255e2b370d89eff7129fcce95f9c6140016e4db3ec98f0054197b464b6edba50943dfbba26a73d5c6698749b43a82e0b828172a1f2275ea94

development: &development
  secret_key_base: 4b746f750ff54b449337e06bdb76637c0e5a0c8141385904a551a6ab5791164d6abe34e516bf8f6c1d10c38cac754bf568d1ac2a9297e6995565a7aa8dbc6efd
  asset_host: 'dxugyqzjahy7a.cloudfront.net'
  content_host: 'dki1hrtf104z9.cloudfront.net'
  google_analytics_key: 'UA-56326872-1'
  invite_codes:
    <<: *invite_codes

staging: &staging
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  asset_host: 'dxugyqzjahy7a.cloudfront.net'
  content_host: 'dki1hrtf104z9.cloudfront.net'
  google_analytics_key: 'UA-56326872-1'
  invite_codes:
    <<: *invite_codes

sandbox:
  <<: *staging
  asset_host: 'vizamyl-sandbox.herokuapp.com'
  invite_codes:
    <<: *invite_codes

production: &production
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  # asset_host: 'assets.readvizamyl.com' # Disabled as GE refused wildcart cert which broke this
  # asset_host: 'd3tnwc4szodljd.cloudfront.net' # Disabled, as cloudfront is not working
  asset_host: 'it.readvizamyl.com' # Serve CSS from Heroku via rails_serve_static_assets
  # content_host: 'content.readvizamyl.com' # Disabled as GE refused wildcart cert which broke this
  content_host: 'djqy74tsvke0j.cloudfront.net' # Serve videos from S3 via cloudfront
  google_analytics_key: 'UA-56326872-2'
  invite_codes:
    <<: *invite_codes
